apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  labels:
    app: sftp
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: sftp

  template:
    metadata:
      labels:
        app: sftp
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sftp
      containers:
      - name: sftp
        image: atmoz/sftp:alpine
        ports:
        - containerPort: 22
        volumeMounts:
        - name: data
          mountPath: "/home/dev_batch"
        env:
        - name: SFTP_USER
          valueFrom:
            secretKeyRef:
              name: sftp
              key: user
        - name: SFTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sftp
              key: password
        - name: HOSTNAME
          valueFrom:
            secretKeyRef:
              name: sftp
              key: host
        - name: SFTP_USERS
          value: "$(SFTP_USER):$(SFTP_PASSWORD):1001:100:batch_dir,\
                  data,data/Discounts,data/termicc,data/termicc/sicc,\
                  data/Discounts/incoming,\
                  data/Discounts/outgoing,\
                  data/termicc/sicc/dout,\
                  Frontal,\
                  Frontal/Descuentos,\
                  Frontal/dextrafolder,\
                  Frontal/prov,\
                  CVM_Retention,CVM_Retention/ATC,CVM_Retention/Codificaciones,CVM_Retention/Empresas,\
                  CVM_Retention/Empresas/codificaciones,CVM_Retention/oferta,\
                  CVM_Retention/ATC/oferta,\
                  CVM_Retention/Codificaciones/AON,\
                  CVM_Retention/Codificaciones/Emergia,\
                  CVM_Retention/Codificaciones/Konecta,\
                  CVM_Retention/Codificaciones/Marktel_Madrid,\
                  CVM_Retention/Codificaciones/Marktel_Valencia,\
                  CVM_Retention/Empresas/codificaciones/AON,\
                  CVM_Retention/Empresas/codificaciones/Emergia,\
                  CVM_Retention/Empresas/codificaciones/Konecta,\
                  CVM_Retention/Empresas/codificaciones/Marktel_Madrid,\
                  CVM_Retention/Empresas/codificaciones/Marktel_Valencia,\
                  CVM_Retention/Empresas/oferta,\
                  CVM_Retention/Empresas/penalizaciones,\
                  CVM_Retention/oferta/Emergia,\
                  CVM_Retention/oferta/Konecta,\
                  CVM_Retention/oferta/Marktel_Valencia,\
                  CVM_Retention/penalizaciones"
