apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
  labels:
    app: sftp
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: sftp

  template:
    metadata:
      labels:
        app: sftp
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sftp
      containers:
      - name: sftp
        image: atmoz/sftp:alpine
        ports:
        - containerPort: 22
        volumeMounts:
        - name: data
          mountPath: "/home/mas-care"
        env:
        - name: SFTP_USER
          valueFrom:
            secretKeyRef:
              name: sftp
              key: user
        - name: SFTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sftp
              key: password
        - name: HOSTNAME
          valueFrom:
            secretKeyRef:
              name: sftp
              key: host
        - name: SFTP_USERS
          value: "$(SFTP_USER):$(SFTP_PASSWORD):1001:100:upload,\
                  data"
